def main():
    firstLayer = []
    doc = FreeCAD.ActiveDocument
    objs = doc.Objects

    #print informations about the objects
    for obj in objs:
        App.Console.PrintMessage(str(obj.TypeId) + " - ")
        App.Console.PrintMessage(str(obj.Name) + "\n")
        for child in obj.OutList:
            App.Console.PrintMessage("Childs\n")
            App.Console.PrintMessage("   - " + str(child.TypeId) + " - ")
            App.Console.PrintMessage(str(child.Name) + "\n")
        for parent in obj.InList:
            App.Console.PrintMessage("Parent\n")
            App.Console.PrintMessage("   -" + str(parent.TypeId) + " - ")
            App.Console.PrintMessage("   -" + str(parent.Name) + "\n\n\n")

    #get the first layer
    for obj in objs:
        if obj.InList == []: #no parents
            firstLayer.append(obj)
    for obj in firstLayer:
        createPovrayCode(obj)

    App.Console.PrintMessage("\n\n" + str(firstLayer[0].TypeId) + "\n\n")

def createPovrayCode(fcObj): #returns the povray code for the object
    if fcObj.TypeId == "Part::Box": #no childs
        x1 = fcObj.Placement.Base.x
        y1 = fcObj.Placement.Base.y
        z1 = fcObj.Placement.Base.z
        x2 = fcObj.Placement.Base.x + int(fcObj.Length)
        y2 = fcObj.Placement.Base.y + int(fcObj.Width)
        z2 = fcObj.Placement.Base.z + int(fcObj.Height)

        povBox = "box{ <"
        povBox += str(x1) + "," + str(y1) + "," + str(z1) + ">, <" + str(x2) + "," + str(y2) + "," + str(z2) + ">\n"
        pigment = """
                    pigment{ checker
                        color rgb<1,1,1>
                        color rgb<1,1,1>*0
                        scale <1.0, 1.0, 1.0> }
                    }\n\n"""
        povBox += pigment;
        App.Console.PrintMessage(povBox)

main()
